parameters:
  string: &string "${STRING}"
  number: &number "${NUMBER}"
  user: &user "${USER}"
  member: &member "${MEMBER}"
  role: &role "${ROLE}"
  channel: &channel "${CHANNEL}"
  remaining: &remaining "${REMAINING}"
  empty: &empty {}

routes:
  none: &none "${NONE}"
  routeless: &routeless "${ROUTELESS}"

command: &command
  desc: ""
  params:
    *none : *empty
  aliases: []

commands:
  help:
    <<: *command
    desc: "Lists commands"
  info:
    <<: *command
    desc: "Displays information about the bot"
  markov:
    <<: *command
    desc: "Markov chain utilities"
    params:
      gen: *empty
      say:
        author: *member
        source: *channel
      scry:
        source: *channel
        amount: *number
      save: *empty
      load: *empty
  settings:
    <<: *command
    desc: "Configuration for the bot"
    aliases:
      - config
      - cfg
  voice:
    <<: *command
    desc: "Lets the bot join voice channels"
    params:
      join:
        voicechannel: *channel
      leave: *empty
  eval:
    <<: *command
    desc: "Evaluates a python statement"
    params:
      *routeless :
        *remaining : *string
  roleinfo:
    <<: *command
    desc: "Displays information about a given role"
    params:
      *routeless :
        role: *role
